export const SET_PERSONAL_INFO_REQUEST = 'SET_PERSONAL_INFO_REQUEST'
export const SET_PERSONAL_INFO_SUCCESS = 'SET_PERSONAL_INFO_SUCCESS'
export const SET_PERSONAL_INFO_FAIL = 'SET_PERSONAL_INFO_FAIL'

export const SET_COMPANY_INFO_REQUEST = 'SET_COMPANY_INFO_REQUEST'
export const SET_COMPANY_INFO_SUCCESS = 'SET_COMPANY_INFO_SUCCESS'
export const SET_COMPANY_INFO_FAIL = 'SET_COMPANY_INFO_FAIL'

export const SET_BRANDINGTYPE_REQUEST = 'SET_BRANDINGTYPE_REQUEST'
export const SET_BRANDINGTYPE_SUCCESS = 'SET_BRANDINGTYPE_SUCCESS'
export const SET_BRANDINGTYPE_FAIL = 'SET_BRANDINGTYPE_FAIL'