export const SET_CAROUSELTYPE_REQUEST = 'SET_CAROUSELTYPE_REQUEST'
export const SET_CAROUSELTYPE_SUCCESS = 'SET_CAROUSELTYPE_SUCCESS'
export const SET_CAROUSELTYPE_FAIL = 'SET_CAROUSELTYPE_FAIL'

export const SET_SLIDETYPE_REQUEST = 'SET_SLIDETYPE_REQUEST'
export const SET_SLIDETYPE_SUCCESS = 'SET_SLIDETYPE_SUCCESS'
export const SET_SLIDETYPE_FAIL = 'SET_SLIDETYPE_FAIL'