export const DOWNLOAD_FILE_REQUEST = 'DOWNLOAD_FILE_REQUEST'
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS'
export const DOWNLOAD_FILE_FAIL = 'DOWNLOAD_FILE_FAIL'

export const DOWNLOAD_TOGGLE_REQUEST = 'DOWNLOAD_TOGGLE_REQUEST'
export const DOWNLOAD_TOGGLE_SUCCESS = 'DOWNLOAD_TOGGLE_SUCCESS'
export const DOWNLOAD_TOGGLE_FAIL = 'DOWNLOAD_TOGGLE_FAIL'