export const SET_FONT_REQUEST = 'SET_FONT_REQUEST'
export const SET_FONT_SUCCESS = 'SET_FONT_SUCCESS'
export const SET_FONT_FAIL = 'SET_FONT_FAIL'

export const SET_FONT_REQUEST2 = 'SET_FONT_REQUEST2'
export const SET_FONT_SUCCESS2 = 'SET_FONT_SUCCESS2'
export const SET_FONT_FAIL2 = 'SET_FONT_FAIL2'

export const GET_FONT_REQUEST = 'GET_FONT_REQUEST'
export const GET_FONT_SUCCESS = 'GET_FONT_SUCCESS'
export const GET_FONT_FAIL = 'GET_FONT_FAIL'

export const CUSTOM_FONT_REQUEST = 'CUSTOM_FONT_REQUEST'
export const CUSTOM_FONT_SUCCESS = 'CUSTOM_FONT_SUCCESS'
export const CUSTOM_FONT_FAIL = 'CUSTOM_FONT_FAIL'

export const SET_CUSTOMFONT_REQUEST = 'SET_CUSTOMFONT_REQUEST'
export const SET_CUSTOMFONT_SUCCESS = 'SET_CUSTOMFONT_SUCCESS'
export const SET_CUSTOMFONT_FAIL = 'SET_CUSTOMFONT_FAIL'