export const SET_LANGUAGE_REQUEST = 'SET_LANGUAGE_REQUEST'
export const SET_LANGUAGE_SUCCESS = 'SET_LANGUAGE_SUCCESS'
export const SET_LANGUAGE_FAIL = 'SET_LANGUAGE_SUCCESS'

export const GET_TRANSLATION_REQUEST = 'GET_TRANSLATION_REQUEST'
export const GET_TRANSLATION_SUCCESS = 'GET_TRANSLATION_SUCCESS'
export const GET_TRANSLATION_FAIL = 'GET_TRANSLATION_FAIL'