export const SET_TEMPLATE_REQUEST = 'SET_TEMPLATE_REQUEST'
export const SET_TEMPLATE_SUCCESS = 'SET_TEMPLATE_SUCCESS'
export const SET_TEMPLATE_FAIL = 'SET_TEMPLATE_FAIL'

export const SET_SINGLESILDETEMPLATE_REQUEST = 'SET_SINGLESILDETEMPLATE_REQUEST'
export const SET_SINGLESILDETEMPLATE_SUCCESS = 'SET_SINGLESILDETEMPLATE_SUCCESS'
export const SET_SINGLESILDETEMPLATE_FAIL = 'SET_SINGLESILDETEMPLATE_FAIL'