export const SET_TEXTSIZE_REQUEST = 'SET_TEXTSIZE_REQUEST'
export const SET_TEXTSIZE_SUCCESS = 'SET_TEXTSIZE_SUCCESS'
export const SET_TEXTSIZE_FAIL = 'SET_TEXTSIZE_FAIL'

export const SET_TEXTALIGN_REQUEST = 'SET_TEXTALIGN_REQUEST'
export const SET_TEXTALIGN_SUCCESS = 'SET_TEXTALIGN_SUCCESS'
export const SET_TEXTALIGN_FAIL = 'SET_TEXTALIGN_FAIL'