export const SET_USER_REQUEST = 'SET_USER_REQUEST'
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS'
export const SET_USER_FAIL = 'SET_USER_FAIL'

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"